// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '1:865028077632:web:82efbc6f2b04bedfbf47a5',
    messagingSenderId: '865028077632',
    projectId: 'polifyx-partner-app',
    storageBucket: 'polifyx-partner-app.appspot.com',
    measurementId: 'G-WV22VQJR3H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNNEL5jfRzTQzzuDrWWOvkCc0MAiAnSqw',
    appId: '1:372522457338:android:b626b06068d805b8219143',
    messagingSenderId: '372522457338',
    projectId: 'myfitness-7c63c',
    storageBucket: '',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNNEL5jfRzTQzzuDrWWOvkCc0MAiAnSqw',
    appId: '1:865028077632:ios:3bba0ba520383664bf47a5',
    messagingSenderId: '865028077632',
    projectId: 'polifyx-partner-app',
    storageBucket: 'polifyx-partner-app.appspot.com',
    androidClientId:
        '865028077632-54tun57hcfo1l4pfdsodt8cdnkgrule6.apps.googleusercontent.com',
    iosClientId:
        '865028077632-q9p71ovr2aev7kbpof3pma37e4o0372n.apps.googleusercontent.com',
    iosBundleId: 'com.partner.polifyx',
  );
}
